name: Rust

on:
  push:
  #  branches: [ master ]
  pull_request:

env:
  AUTH: ${{secrets.VP_DEPLOY_USER}}:${{secrets.VP_DEPLOY_SECRET}}
  CARGO_TERM_COLOR: always
  REPO: ${{secrets.DEPLOY_REPO}}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install GStreamer
        run: |
          sudo apt update && \
          sudo apt install -y \
            libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev \
            gstreamer1.0-plugins-base gstreamer1.0-plugins-good \
            gstreamer1.0-plugins-bad gstreamer1.0-libav libgstrtspserver-1.0-dev \
            libssl-dev libges-1.0-dev
      - uses: actions/checkout@v3
#      - name: Build
#        run: cargo build --verbose
      #- name: Run Clippy
      #  run: cargo clippy --no-deps
      #- name: Run tests
      #  run: cargo test --verbose
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Deploy Lyle Maybe
        if: github.event_name != 'pull_request'
        run: |
          curl -XPOST -u "${AUTH}" -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${REPO}/dispatches -d '{"event_type": "lyle"}'
      #- name: Deploy Dev
      #  run: |
      #    curl -XPOST -u "${AUTH}" -H "Accept: application/vnd.github.v3+json" \
      #      https://api.github.com/repos/${REPO}/dispatches -d '{"event_type": "dev"}'
